export const typeAction = {
  SIGNUP : "SIGNUP",
  ERROR_SIGNUP : "ERROR_SIGNUP",
  LOGIN : "LOGIN",
  ERROR_LOGIN : "ERROR_LOGIN",
  SET_MODAL:"SET_MODAL",
  SET_LOADING:"SET_LOADING",
  IS_LOGIN:"IS_LOGIN",

  LOGOUT : "LOGOUT",

  GET_PROFILE:"GET_PROFILE",
  GET_PRODUCT:"GET_PRODUCT",
  GET_PRODUCT_ID:"GET_PRODUCT_ID",
  GET_PRODUCT_FAVORITE:"GET_PRODUCT_FAVORITE",
  REMOVE_STATE:"REMOVE_STATE",

  SET_LIKE:"SET_LIKE",
  SET_UNLIKE:"SET_UNLIKE",

  ADD_CART:"ADD_CART",
  DELETE_ITEM_CART:"DELETE_ITEM_CART",
  DELETE_ALL_CART:"DELETE_ALL_CART",
  ORDER:"ORDER",
  DELETE_ORDER:"DELETE_ORDER",

  UPDATE_USER:"UPDATE_USER",
  UPLOAD_AVATAR:"UPLOAD_AVATAR",


  DECREASE:"DECREASE",
  INCREASE:"INCREASE",


};
